### ISSUE TITLE
Project doesn't compile

### ISSUE THREAD

**Issue by Septias** [rustyscreeps/screeps-starter-rust#18]
Yesterday, the project compiled for me but since this morning the project doesn't compile because of this error: 

`error: linking with 'link.exe' failed: exit code: 1120`

I updated rust using rustup update to install rustfmt and clippy - I guess that is the issue, but how do I solve it?

**Comment by ASalvail** [comment]
Maybe clearing the cache? If it worked on stable before, I'd hate for an
update to have broken the build.

**Comment by Septias** [comment]
I deleted the target folder and lock file but that doesn't solve the issue.
I even downloaded a fresh copy which also didn't compile :/

**Comment by Septias** [comment]
Oh wait, I'm so sorry ._. I didn't build it using cargo screeps, I just ran cargo build 😆. So I guess that was the issue...

**Comment by ASalvail** [comment]
Haha, no worries, I'm just glad it works now for you.
