### ISSUE TITLE
panicked at 'unknown name section chunk type: 7'

### ISSUE THREAD

**Issue by Septias** [rustyscreeps/screeps-starter-rust#25]
At the current version I get "thread 'main' panicked at 'unknown name section chunk type: 7', C:\Users\score\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-web-0.6.26\src\wasm_context.rs:642:41" when building using
` cargo screeps build`

Is there a solution to this?

**Comment by Azaril** [comment]
Which version of rust are you using? I think beyond something like 1.47 cargo web is busted. There's an effort to convert to bindgen but in the meantime you may just want to pin your rust version for the project.

**Comment by Septias** [comment]
yeah that solved it, ty
